name: Quickstart Github Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    # TODO: Replace with release based trigger when done developing
    branches: ['main']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  quickstart-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Basic runner info
        run: |
          echo "Trigger event: ${{ github.event_name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Branch: ${{ github.ref }}"

      # Enables multi-platform support in docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.0
      - name: Check install!
        run: cosign version

      # Necessary to support subdirs in context of `Build and push Docker image` step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Context implicitly checks out repo. Be aware, that every
      # operation perfomed on repo-data will be reset by the implicit
      # checkout (see https://github.com/docker/build-push-action#git-context)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{ defaultContext }}:build"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
